### ISSUE TITLE
LỖI - Chức năng xuất điều về từ kho lẻ bị mất giá bhyt

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalsecondstore#4]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **6/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_giabhyt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `02` - _**MaHH**_: `BI93` - _**SoHD**_: `DD8.00001/10` - _**NgayHD**_: `06/10/2022` - _**ThangKT**_: `10` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Thuốc tại kho lẻ tồn kho có giá bhyt nhưng khi xuất điều về kho chẳn thì giá bhyt = 0

```
Tồn kho lẻ
![image](https://user-images.githubusercontent.com/96155021/194193729-778177be-2324-4b3a-94bc-ae524cca5df2.png)
Chứng từ xuất điều về
![image](https://user-images.githubusercontent.com/96155021/194193790-1685a43f-6f60-4109-8b6f-a2b80f28a5a7.png)
Nhận chứng từ ở Medicine không có giá bhyt
![image](https://user-images.githubusercontent.com/96155021/194193871-9a944710-b046-4b1a-b41a-60409c95f06c.png)
Tồn kho chẳn sau khi nhập
![image](https://user-images.githubusercontent.com/96155021/194193921-295ecb8c-f8d9-476a-b6be-611b66b8872a.png)

**Comment by nghivanbi** [comment]
Cập nhật
SecondStore: [v3.22.1027.1](http://www.fsend.vn/download/jqXPWmraZewWAMhfOhHVS25DmrAtRn0X)

**Comment by le-an-87** [comment]
đã fix!
