### ISSUE TITLE
Yêu cầu - Kiểm tra cấu trúc âm kho.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalsecondstore#9]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Phước Long**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbphuoclong_bli`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Đề nghị khi đăng nhập thành công thì kiểm tra xem cấu trúc âm kho có được tạo hay chưa, nếu chưa thì tự động tạo lại, nếu trường hợp tạo lại bị lỗi do đang có mặt hàng bị âm thì cảnh báo cho người dùng liên hệ quản trị hệ thống.

**Comment by lqbinh1987** [comment]
Chổ này như thống nhất trong cuộc họp thì làm cảnh báo mỗi lần đăng nhập, nhờ anh @nghivanbi duyệt dùm em để bổ sung cho BV.

**Comment by nghivanbi** [comment]
Này thống nhất thực hiện như sau:
- Medicine sẽ kiểm tra khóa chưa có sẽ báo.
- Admin bổ sung thêm phần ghi nhất ký khi: xóa, tạo lại check kiểm tra này.

**Comment by lqbinh1987** [comment]
Anh @nghivanbi, anh @ongtrieuhau Cho em xin cái deadline dể em báo cho BV biết á anh?

**Comment by ongtrieuhau** [comment]
Cập nhật Admin: [3.23.0623.2](https://github.com/dh-hos/dhg.hospitaladmin/commit/beb2f1c48ed41d514ebd11631f51653f086e55cc)

**Comment by nghivanbi** [comment]
Med: 26/06 nhé

**Comment by nghivanbi** [comment]
Cập nhật:
Medicine:[ v3.23.0625.1](http://www.fsend.vn/download/Wt7XAbAILVHhQYZH0u8P-kgsR1qXxcX5)
